packages:
  - 'charts'
  - 'flows'
  - 'react'
  - 'scaffold'
  - 'tailwind'
  - 'tsconfig'
  - 'types'
  - 'utils'

catalog:
  '@types/node': ^22.13.4
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.5
  tsup: ^8.3.6
  react: ^18.3.1
  react-dom: ^18.3.1
