packages:
  - "charts"
  - "flows"
  - "react"
  - "scaffold"
  - "tailwind"
  - "tsconfig"
  - "types"
  - "utils"
catalog:
  "@xyflow/react": ^12.4.3
  "@emotion/css": ^11.13.5
  "@types/node": ^22.13.4
  "@types/postcss-import": ^14.0.3
  "@tailwindcss/typography": ^0.5.16
  "@types/react": ^18.3.18
  "@types/react-dom": ^18.3.5
  "@types/react-syntax-highlighter": ^15.5.13
  "@commitlint/cli": ^19.7.1
  "@commitlint/config-conventional": ^19.7.1
  "@eslint/compat": ^1.2.6
  "@eslint/eslintrc": ^3.2.0
  "@eslint/js": ^9.20.0
  "@typescript-eslint/eslint-plugin": ^8.24.1
  "@tabler/icons-react": ^3.30.0
  "@tanstack/react-table": ^8.21.2
  autoprefixer: ^10.4.20
  cssnano: ^7.0.6
  postcss: ^8.5.2
  postcss-import: ^16.1.0
  postcss-nesting: ^13.0.1
  eslint: ^9.20.1
  eslint-config-prettier: ^9.1.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-prettier: ^5.2.3
  eslint-plugin-react: ^7.37.4
  globals: ^15.15.0
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  date-fns: ^4.1.0
  jsencrypt: ^3.3.2
  nanoid: ^5.1.0
  husky: ^9.1.7
  lint-staged: ^15.4.3
  prettier: ^3.5.1
  rimraf: ^6.0.1
  turbo: ^2.4.2
  typescript: ^5.7.3
  tsup: ^8.3.6
  echarts: ^5.6.0
  apexcharts: ^4.4.0
  recharts: ^2.15.1
  react: ^18.3.1
  react-dom: ^18.3.1
  react-dropzone: ^14.3.5
  react-hook-form: ^7.54.2
  react-apexcharts: ^1.7.0
  react-day-picker: ^8.10.1
  react-syntax-highlighter: ^15.6.1
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  tailwind-merge: ^3.0.1
  sonner: ^1.7.4
  vaul: ^1.1.2
